version: "3.6"

services:
  proxy:
    image: nginx:stable-alpine
    restart: always
    ports:
      - ${PROXY_PORT}:80
    volumes:
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/code

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/code
      - /code/node_modules
