import Link from "next/link";
import UserProfile from "@/components/UserProfile";
import CustomQueryProvider from "./CustomQueryProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomQueryProvider>
          <UserProfile />
          <div>
            <Link href={`/products`}>Продукты</Link>
          </div>
          <div>
            <Link href={`/`}>Группы</Link>
          </div>
          {children}
        </CustomQueryProvider>
      </body>
    </html>
  );
}
